// Client-side search — a line-for-line port of Services/SearchService.cs, kept as one file so the
// two are easy to diff against each other by eye. Moved client-side ahead of the eventual Azure
// Static Web Apps migration, which has no server runtime at all to run the C# version on; see
// docs/DEVELOPMENT-NOTES.md, which already called this out as the one thing that would need
// rebuilding. Every constant, weight and regex below matches SearchService.cs's C# exactly — this
// is not a fresh take on "some search", it is the same algorithm running in a different language.
//
// The index (wwwroot/data/search-index.json) is a BUILD-TIME artefact, not generated by this
// running site — see the `--generate-search-index` branch in Program.cs. Regenerate it whenever
// content changes; this module only ever reads the committed file.
//
// Same enhanced-navigation problem boot.js/theme.js already solved: blazor.web.js swaps the DOM on
// an internal link without a full page load, so this hooks 'enhancedload' the same way, rather
// than relying on DOMContentLoaded (which only fires on a hard load).

const SNIPPET_RADIUS = 90;
const MAX_RESULTS = 60;

let indexPromise = null;

function loadIndex() {
    if (!indexPromise) {
        // Relative, not root-absolute - see the matching note in demos/model.js (docs/ADR-003).
        indexPromise = fetch('data/search-index.json').then(r => r.json());
    }
    return indexPromise;
}

function splitTerms(query) {
    const seen = new Set();
    const terms = [];
    for (const raw of query.split(/[ \t,;]+/)) {
        const term = raw.trim();
        if (term.length <= 1) continue;
        const key = term.toLowerCase();
        if (seen.has(key)) continue;
        seen.add(key);
        terms.push(term);
    }
    return terms;
}

function countOccurrences(text, term) {
    const needle = term.toLowerCase();
    const haystack = text.toLowerCase();
    let count = 0;
    let index = 0;
    while ((index = haystack.indexOf(needle, index)) >= 0) {
        count++;
        index += needle.length;
        if (count >= 50) break; // enough to know it is a strong match
    }
    return count;
}

const HEADING_PATTERN = /^#{1,6}\s+(.*)$/gm;

function scoreTerm(page, term) {
    const termLower = term.toLowerCase();
    let score = 0;

    const titleLower = page.title.toLowerCase();
    if (titleLower.includes(termLower)) {
        // An exact title match is almost always what the reader wanted.
        score += titleLower === termLower ? 200 : 80;
    }

    if (page.summary && page.summary.toLowerCase().includes(termLower)) score += 20;

    // Slug matches catch terms that appear in the page's location but not its prose.
    if (page.slug.toLowerCase().includes(termLower)) score += 10;

    const occurrences = countOccurrences(page.markdown, term);
    if (occurrences > 0) score += Math.min(30, 5 + occurrences);

    // A term appearing in a heading is a strong signal about what the page covers.
    HEADING_PATTERN.lastIndex = 0;
    let heading;
    while ((heading = HEADING_PATTERN.exec(page.markdown)) !== null) {
        if (heading[1].toLowerCase().includes(termLower)) { score += 25; break; }
    }

    return score;
}

function search(pages, query) {
    const terms = splitTerms(query ?? '');
    if (terms.length === 0) return [];

    const results = [];
    for (const page of pages) {
        let score = 0;
        let matchedEveryTerm = true;

        for (const term of terms) {
            const termScore = scoreTerm(page, term);
            if (termScore === 0) matchedEveryTerm = false;
            score += termScore;
        }

        if (score === 0) continue;

        // Pages matching all terms rank above those matching only some.
        if (matchedEveryTerm) score += 50;

        results.push({
            slug: page.slug,
            title: page.title,
            section: page.section,
            snippet: buildSnippet(page, terms),
            score
        });
    }

    results.sort((a, b) => b.score - a.score || a.title.toLowerCase().localeCompare(b.title.toLowerCase()));
    return results.slice(0, MAX_RESULTS);
}

/** A plain-text extract around the first matching term, with the matches marked. */
function buildSnippet(page, terms) {
    const text = toPlainText(page.markdown);

    let at = -1;
    for (const term of terms) {
        const found = text.toLowerCase().indexOf(term.toLowerCase());
        if (found >= 0 && (at < 0 || found < at)) at = found;
    }

    if (at < 0) {
        const opening = text.length <= SNIPPET_RADIUS * 2 ? text : text.slice(0, SNIPPET_RADIUS * 2) + '…';
        return [{ text: opening, isMatch: false }];
    }

    const start = Math.max(0, at - SNIPPET_RADIUS);
    const end = Math.min(text.length, at + SNIPPET_RADIUS);
    let window = text.slice(start, end);

    if (start > 0) window = '…' + window;
    if (end < text.length) window += '…';

    return highlight(window, terms);
}

/** Splits text into matched and unmatched runs, so the caller decides how to mark them up. */
function highlight(text, terms) {
    const lowerText = text.toLowerCase();
    const spans = [];

    for (const term of terms) {
        const needle = term.toLowerCase();
        let index = 0;
        while ((index = lowerText.indexOf(needle, index)) >= 0) {
            spans.push({ start: index, length: needle.length });
            index += needle.length;
        }
    }

    if (spans.length === 0) return [{ text, isMatch: false }];

    spans.sort((a, b) => a.start - b.start);

    const parts = [];
    let cursor = 0;

    for (const { start, length } of spans) {
        if (start < cursor) continue; // overlapping match already covered

        if (start > cursor) parts.push({ text: text.slice(cursor, start), isMatch: false });
        parts.push({ text: text.slice(start, start + length), isMatch: true });
        cursor = start + length;
    }

    if (cursor < text.length) parts.push({ text: text.slice(cursor), isMatch: false });

    return parts;
}

const IMAGE_PATTERN = /!\[[^\]]*\]\([^)]*\)/g;
const LINK_PATTERN = /\[([^\]]*)\]\([^)]*\)/g;
const FENCE_PATTERN = /```[\s\S]*?```/g;
const MARKUP_PATTERN = /[#*_`>|]|^\s*[-+]\s/gm;
const WHITESPACE_PATTERN = /\s+/g;

/** Strips Markdown syntax so snippets read as prose rather than markup. */
function toPlainText(markdown) {
    let text = markdown.replace(IMAGE_PATTERN, '');
    text = text.replace(LINK_PATTERN, '$1');
    text = text.replace(FENCE_PATTERN, ' ');
    text = text.replace(MARKUP_PATTERN, '');
    text = text.replace(WHITESPACE_PATTERN, ' ');
    return text.trim();
}

/* --------------------------------------------------------------------------------- rendering --- */

function element(tag, className, text) {
    const node = document.createElement(tag);
    if (className) node.className = className;
    if (text !== undefined) node.textContent = text;
    return node;
}

function renderSnippet(parts) {
    const p = element('p', 'result-snippet');
    for (const part of parts) {
        p.appendChild(part.isMatch ? element('mark', null, part.text) : document.createTextNode(part.text));
    }
    return p;
}

function renderResults(container, query, results) {
    container.textContent = '';

    if (results.length === 0) {
        const lede = element('p', 'lede');
        lede.appendChild(document.createTextNode('No results for '));
        lede.appendChild(element('strong', null, query));
        lede.appendChild(document.createTextNode('.'));
        container.appendChild(lede);

        const hint = element('p');
        hint.appendChild(document.createTextNode('Try a shorter or more general term — searching for '));
        hint.appendChild(element('em', null, 'legend'));
        hint.appendChild(document.createTextNode(' will find more than '));
        hint.appendChild(element('em', null, 'legend limit settings'));
        hint.appendChild(document.createTextNode('.'));
        container.appendChild(hint);
        return;
    }

    const lede = element('p', 'lede');
    lede.appendChild(document.createTextNode(`${results.length} result${results.length === 1 ? '' : 's'} for `));
    lede.appendChild(element('strong', null, query));
    lede.appendChild(document.createTextNode('.'));
    container.appendChild(lede);

    const list = element('ol', 'results');
    for (const result of results) {
        const li = element('li', 'result');

        const link = element('a', 'result-title', result.title);
        link.href = `/docs/${result.slug}`;
        li.appendChild(link);

        if (result.section) li.appendChild(element('span', 'result-section', result.section));

        li.appendChild(renderSnippet(result.snippet));
        list.appendChild(li);
    }
    container.appendChild(list);
}

async function runSearch() {
    const container = document.getElementById('search-results');
    if (!container) return; // not on the search page

    const query = new URLSearchParams(location.search).get('q')?.trim();
    if (!query) return; // leave the server-rendered "search across every page" message in place

    const pages = await loadIndex();
    renderResults(container, query, search(pages, query));
}

runSearch();

if (window.Blazor && typeof Blazor.addEventListener === 'function') {
    Blazor.addEventListener('enhancedload', runSearch);
}
